name: Run a.py Every 5 Minutes
on: push
permissions:
  contents: write

jobs:
  npm-build:
    name: npm-build工作
    runs-on: ubuntu-latest
    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install
        run: pip3 install requests
      - name: Run a.py
        run: python a.py
      - name: 部署
        uses: JamesIves/github-pages-deploy-action@v4  # 修正可能的拼写错误（原图显示为 lves）
        with:
          branch: node
          folder: ./  # 补充缺失的构建目录字段（React 默认 build/ 目录）

