name: Run a.py Every 5 Minutes
on:
  schedule:
    - cron: '*/5 * * * *'  # UTC时间，每5分钟运行一次[1,5](@ref)
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run a.py
        run: python a.py
